# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Maven version check
        run: mvn -X -version
      - name: Checkout mod
        uses: actions/checkout@v3
        with:
          path: shadow-exploits-showcase-1.19.2
      - name: Grant execute permission for gradlew
        working-directory: shadow-exploits-showcase-1.19.2
        run: chmod +x gradlew
      - name: Build Mod
        working-directory: shadow-exploits-showcase-1.19.2
        run: ./gradlew build
